/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeistungenWebseitenBrandingRouteImport } from './routes/leistungen/webseiten-branding'
import { Route as LeistungenSichtbarkeitSteigernRouteImport } from './routes/leistungen/sichtbarkeit-steigern'
import { Route as LeistungenKiAutomatisierungRouteImport } from './routes/leistungen/ki-automatisierung'
import { Route as LeistungenDigitaleWerbungRouteImport } from './routes/leistungen/digitale-werbung'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenWebseitenBrandingRoute =
  LeistungenWebseitenBrandingRouteImport.update({
    id: '/leistungen/webseiten-branding',
    path: '/leistungen/webseiten-branding',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenSichtbarkeitSteigernRoute =
  LeistungenSichtbarkeitSteigernRouteImport.update({
    id: '/leistungen/sichtbarkeit-steigern',
    path: '/leistungen/sichtbarkeit-steigern',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenKiAutomatisierungRoute =
  LeistungenKiAutomatisierungRouteImport.update({
    id: '/leistungen/ki-automatisierung',
    path: '/leistungen/ki-automatisierung',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenDigitaleWerbungRoute =
  LeistungenDigitaleWerbungRouteImport.update({
    id: '/leistungen/digitale-werbung',
    path: '/leistungen/digitale-werbung',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/partner': typeof PartnerRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/digitale-werbung': typeof LeistungenDigitaleWerbungRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/leistungen/sichtbarkeit-steigern': typeof LeistungenSichtbarkeitSteigernRoute
  '/leistungen/webseiten-branding': typeof LeistungenWebseitenBrandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/partner': typeof PartnerRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/digitale-werbung': typeof LeistungenDigitaleWerbungRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/leistungen/sichtbarkeit-steigern': typeof LeistungenSichtbarkeitSteigernRoute
  '/leistungen/webseiten-branding': typeof LeistungenWebseitenBrandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/partner': typeof PartnerRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/digitale-werbung': typeof LeistungenDigitaleWerbungRoute
  '/leistungen/ki-automatisierung': typeof LeistungenKiAutomatisierungRoute
  '/leistungen/sichtbarkeit-steigern': typeof LeistungenSichtbarkeitSteigernRoute
  '/leistungen/webseiten-branding': typeof LeistungenWebseitenBrandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/partner'
    | '/ueber-uns'
    | '/leistungen/digitale-werbung'
    | '/leistungen/ki-automatisierung'
    | '/leistungen/sichtbarkeit-steigern'
    | '/leistungen/webseiten-branding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/partner'
    | '/ueber-uns'
    | '/leistungen/digitale-werbung'
    | '/leistungen/ki-automatisierung'
    | '/leistungen/sichtbarkeit-steigern'
    | '/leistungen/webseiten-branding'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/partner'
    | '/ueber-uns'
    | '/leistungen/digitale-werbung'
    | '/leistungen/ki-automatisierung'
    | '/leistungen/sichtbarkeit-steigern'
    | '/leistungen/webseiten-branding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PartnerRoute: typeof PartnerRoute
  UeberUnsRoute: typeof UeberUnsRoute
  LeistungenDigitaleWerbungRoute: typeof LeistungenDigitaleWerbungRoute
  LeistungenKiAutomatisierungRoute: typeof LeistungenKiAutomatisierungRoute
  LeistungenSichtbarkeitSteigernRoute: typeof LeistungenSichtbarkeitSteigernRoute
  LeistungenWebseitenBrandingRoute: typeof LeistungenWebseitenBrandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/webseiten-branding': {
      id: '/leistungen/webseiten-branding'
      path: '/leistungen/webseiten-branding'
      fullPath: '/leistungen/webseiten-branding'
      preLoaderRoute: typeof LeistungenWebseitenBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/sichtbarkeit-steigern': {
      id: '/leistungen/sichtbarkeit-steigern'
      path: '/leistungen/sichtbarkeit-steigern'
      fullPath: '/leistungen/sichtbarkeit-steigern'
      preLoaderRoute: typeof LeistungenSichtbarkeitSteigernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/ki-automatisierung': {
      id: '/leistungen/ki-automatisierung'
      path: '/leistungen/ki-automatisierung'
      fullPath: '/leistungen/ki-automatisierung'
      preLoaderRoute: typeof LeistungenKiAutomatisierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/digitale-werbung': {
      id: '/leistungen/digitale-werbung'
      path: '/leistungen/digitale-werbung'
      fullPath: '/leistungen/digitale-werbung'
      preLoaderRoute: typeof LeistungenDigitaleWerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PartnerRoute: PartnerRoute,
  UeberUnsRoute: UeberUnsRoute,
  LeistungenDigitaleWerbungRoute: LeistungenDigitaleWerbungRoute,
  LeistungenKiAutomatisierungRoute: LeistungenKiAutomatisierungRoute,
  LeistungenSichtbarkeitSteigernRoute: LeistungenSichtbarkeitSteigernRoute,
  LeistungenWebseitenBrandingRoute: LeistungenWebseitenBrandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
